frontend:
  replicaCount: 1
  image:
    repository: madhavdhatrak/gitops-frontend
    tag: 8061b88
    pullPolicy: Always
  service:
    type: NodePort
    port: 5173
    targetPort: 5173
    nodePort: 30000
  config:
    apiUrl: /api
backend:
  replicaCount: 1
  image:
    repository: madhavdhatrak/gitops-backend
    tag: 8061b88
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 5000
    targetPort: 5000
  config:
    port: 5000
