# .github/workflows/ci-cd.yaml
name: Build-and-Sync

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Decide image tag (short SHA)
        id: vars
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build & push frontend
        uses: docker/build-push-action@v4
        with:
          context: app/frontend
          push: true
          tags: madhavdhatrak/gitops-frontend:${{ steps.vars.outputs.TAG }}

      - name: Build & push backend
        uses: docker/build-push-action@v4
        with:
          context: app/backend
          push: true
          tags: madhavdhatrak/gitops-backend:${{ steps.vars.outputs.TAG }}

      - name: Install yq
        run: sudo apt-get update && sudo apt-get install -y yq

      - name: Bump image tags in Helm chart
        run: |
          yq -i '.frontend.image.tag = "${{ steps.vars.outputs.TAG }}"'  myapp/values.yaml
          yq -i '.backend.image.tag  = "${{ steps.vars.outputs.TAG }}"'  myapp/values.yaml

      - name: Commit and push chart change
        run: |
          git config user.email "actions@github.com"
          git config user.name  "GitHub Actions"
          git add myapp/values.yaml
          git commit -m "chore: update image tags to ${{ steps.vars.outputs.TAG }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 